# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Main

"on":
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish Main
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d  # v0.9
        with:
          version: v0.18.0
      - name: Build and publish project-api image
        env:
          VERSION: development
          GIT_COMMIT: ${{ github.sha }}
        run: |
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          export BUILD_TIME
          GIT_COMMIT=${GIT_COMMIT:0:7}
          export GIT_COMMIT
          ko build github.com/linuxfoundation/lfx-v2-project-service/cmd/project-api \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t development \
            --sbom spdx
      - run: |
          ko build github.com/linuxfoundation/lfx-v2-project-service/scripts/root-project-setup \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t ${{ github.sha }} \
            -t development \
            --sbom spdx
